apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: sevhh6jen-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sevhh6jen-go 
  name: sevhh6jen-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: sevhh6jen-go 
